### PR TITLE
How about using libraries-bom 3.2.0?

### PR DESCRIPTION
**Pull request by suztomo**
How about using libraries-bom 3.2.0? The BOM includes grpc-bom and protobuf-bom. This is one potential answer to the question in https://github.com/googleapis/java-bigtable-hbase/pull/2336#issuecomment-570612885

### CODE REVIEW

**Comment by suztomo** [comment]
Test fails

```
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ bigtable-hbase-1.x-hadoop ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.cloud.bigtable.hbase.TestBigtableConnection
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.148 s <<< FAILURE! - in com.google.cloud.bigtable.hbase.TestBigtableConnection
[ERROR] testOpenSSL(com.google.cloud.bigtable.hbase.TestBigtableConnection)  Time elapsed: 0.054 s  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at com.google.cloud.bigtable.hbase.TestBigtableConnection.testOpenSSL(TestBigtableConnection.java:77)
[ERROR] testTable(com.google.cloud.bigtable.hbase.TestBigtableConnection)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at com.google.cloud.bigtable.hbase.TestBigtableConnection.testTable(TestBigtableConnection.java:66)
[ERROR] testBigtableConnectionExists(com.google.cloud.bigtable.hbase.TestBigtableConnection)  Time elapsed: 0.016 s  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at com.google.cloud.bigtable.hbase.TestBigtableConnection.testBigtableConnectionExists(TestBigtableConnection.java:39)
[ERROR] testConfig_AppProfile(com.google.cloud.bigtable.hbase.TestBigtableConnection)  Time elapsed: 0.011 s  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at com.google.cloud.bigtable.hbase.TestBigtableConnection.testConfig_AppProfile(TestBigtableConnection.java:55)
[ERROR] testConfig_Basic(com.google.cloud.bigtable.hbase.TestBigtableConnection)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at com.google.cloud.bigtable.hbase.TestBigtableConnection.testConfig_Basic(TestBigtableConnection.java:44)
```

Even if I skip tests,

**Comment by suztomo** [comment]
Even if I skip tests, the build fails at shade plugin at bigtable-hbase-1.x-hadoop:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for com.google.cloud.bigtable:bigtable-client-parent 1.12.2-SNAPSHOT:
[INFO] 
[INFO] com.google.cloud.bigtable:bigtable-client-parent ... SUCCESS [  0.223 s]
[INFO] com.google.cloud.bigtable:bigtable-client-core-parent SUCCESS [  0.028 s]
[INFO] com.google.cloud.bigtable:bigtable-client-core ..... SUCCESS [  2.815 s]
[INFO] com.google.cloud.bigtable:bigtable-hbase ........... SUCCESS [  1.151 s]
[INFO] com.google.cloud.bigtable:bigtable-hbase-integration-tests-common SUCCESS [  0.713 s]
[INFO] com.google.cloud.bigtable:bigtable-hbase-1.x-parent  SUCCESS [  0.030 s]
[INFO] com.google.cloud.bigtable:bigtable-hbase-1.x ....... SUCCESS [  0.456 s]
[INFO] bigtable-hbase-1.x-shaded .......................... SUCCESS [  9.114 s]
[INFO] bigtable-hbase-1.x-hadoop .......................... FAILURE [  0.409 s]
[INFO] com.google.cloud.bigtable:bigtable-hbase-1.x-integration-tests SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-hbase-1.x-mapreduce SKIPPED
[INFO] bigtable-hbase-1.x-benchmarks ...................... SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-hbase-2.x-parent  SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-hbase-2.x ....... SKIPPED
[INFO] bigtable-hbase-2.x-shaded .......................... SKIPPED
[INFO] bigtable-hbase-2.x-hadoop .......................... SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-hbase-2.x-integration-tests SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-dataflow-parent . SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-hbase-beam ...... SKIPPED
[INFO] bigtable-beam-import ............................... SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-test ............ SKIPPED
[INFO] com.google.cloud.bigtable:bigtable-emulator-maven-plugin SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.182 s
[INFO] Finished at: 2020-01-03T13:44:07-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.1:shade (default) on project bigtable-hbase-1.x-hadoop: Error creating shaded jar: Problem shading JAR /usr/local/google/home/suztomo/java-bigtable-hbase/bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/target/bigtable-hbase-1.x-shaded-1.12.2-SNAPSHOT.jar entry META-INF/MANIFEST.MF: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.1:shade (default) on project bigtable-hbase-1.x-hadoop: Error creating shaded jar: Problem shading JAR /usr/local/google/home/suztomo/java-bigtable-hbase/bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/target/bigtable-hbase-1.x-shaded-1.12.2-SNAPSHOT.jar entry META-INF/MANIFEST.MF: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

```

**Comment by igorbernstein2** [comment]
We are planning on using this bom instead:
https://github.com/googleapis/java-bigtable/tree/master/google-cloud-bigtable-deps-bom

I would like to keep the versions in java-bigtable & java-bigtable-hbase tightly synchronized and using libraries bom will introduce an unnecessary release schedule into the mix.

**Comment by suztomo** [comment]
@igorbernstein2 Thank you for response. That'll also good for me.

**Pull request closed without merging**
