### PR TITLE
deps: migrate to log4j-core

### PR DESCRIPTION
**Pull request by kolea2**

### CODE REVIEW

**Review by vermas2012 — COMMENTED** [review]
How have you tested this change?

**Review by vermas2012 — APPROVED** [review]
Overall changes look good. Approved, provided we have tested the logging for the tool.

**Comment by kolea2** [comment]
> Overall changes look good. Approved, provided we have tested the logging for the tool.

Thanks @vermas2012 for taking a look! I tried some testing and realized I had to make a few additional fixes. I was able to successfully get this to work by running the unit tests with the log4j2.xml file uncommented. I did change this to STDOUT as the output - is this ok?

**Comment by vermas2012** [comment]
STDout is fine. I wonder if we should test logging by running the actual tool?

**Comment by vermas2012** [comment]
> STDout is fine. I wonder if we should test logging by running the actual tool?

You don't have to setup HBase, you can use this json file as a source for schema
[schema-2.json.zip](https://github.com/googleapis/java-bigtable-hbase/files/7549676/schema-2.json.zip)
.

**Pull request merged**
